export const AREAS_ATUACAO = [
  "Administrador(a)",
  "Advogado(a)",
  "Analista de Marketing",
  "Analista de Sistemas",
  "Arquiteto(a)",
  "Assistente Social",
  "Autônomo(a)",
  "Contador(a)",
  "Dentista",
  "Desenvolvedor(a) de Software",
  "Designer",
  "Economista",
  "Enfermeiro(a)",
  "Engenheiro(a)",
  "Estudante",
  "Farmacêutico(a)",
  "Fisioterapeuta",
  "Gerente de Projetos",
  "Jornalista",
  "Médico(a)",
  "Nutricionista",
  "Produtor(a) de Conteúdo",
  "Professor(a)",
  "Psicólogo(a)",
  "Publicitário(a)",
  "Recursos Humanos",
  "Servidor(a) Público(a)",
  "Vendedor(a)",
  "Veterinário(a)",
  "Outro",
] as const;
